//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrator.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Migrator.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done! ({0} s).
        /// </summary>
        public static string CompletedMigrationMessage {
            get {
                return ResourceManager.GetString("CompletedMigrationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connection string is required.
        /// </summary>
        public static string ConnectionStringIsRequired {
            get {
                return ResourceManager.GetString("ConnectionStringIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load runner factory &apos;{0}&apos;.
        /// </summary>
        public static string CouldNotCreateRunnerFactoryType {
            get {
                return ResourceManager.GetString("CouldNotCreateRunnerFactoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load runner assembly &apos;{0}&apos;.
        /// </summary>
        public static string CouldNotLoadRunnerAssemblyFormat {
            get {
                return ResourceManager.GetString("CouldNotLoadRunnerAssemblyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors were encountered:.
        /// </summary>
        public static string ErrorHeading {
            get {
                return ResourceManager.GetString("ErrorHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Url: https://github.com/MatthewLymer/ScriptMigrations
        ///
        ///Example: Migrator.Console.exe /up /runner=&quot;assembly, namespace.type&quot; /connectionstring=&quot;my-connection-string&quot; /scripts=&quot;C:/my-scripts&quot;
        ///
        ///[/up] 
        ///Perform all up migrations that have not yet been run on target database, in ascending order.
        ///
        ///[/down /version=X]
        ///Perform down migrations that have been run on target database, in descending order, where the migration version is greater than X.  Migration with version X must exist in database or be [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HelpUsage {
            get {
                return ResourceManager.GetString("HelpUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot migrate up and down at the same time.
        /// </summary>
        public static string MigrateUpDownMutuallyExclusive {
            get {
                return ResourceManager.GetString("MigrateUpDownMutuallyExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration for runner is not valid..
        /// </summary>
        public static string RunnerFactoryTestQueryFailedMessage {
            get {
                return ResourceManager.GetString("RunnerFactoryTestQueryFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to runner qualified name is not expected format.
        /// </summary>
        public static string RunnerQualifiedNameBadFormat {
            get {
                return ResourceManager.GetString("RunnerQualifiedNameBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to runner qualified name is required.
        /// </summary>
        public static string RunnerQualifiedNameIsRequired {
            get {
                return ResourceManager.GetString("RunnerQualifiedNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scripts path is required.
        /// </summary>
        public static string ScriptsPathIsRequired {
            get {
                return ResourceManager.GetString("ScriptsPathIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot show help and migrate at the same time.
        /// </summary>
        public static string ShowHelpMigrateMutuallyExclusive {
            get {
                return ResourceManager.GetString("ShowHelpMigrateMutuallyExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting migration {0}, &apos;{1}&apos;... .
        /// </summary>
        public static string StartingMigrationMessageFormat {
            get {
                return ResourceManager.GetString("StartingMigrationMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version is required.
        /// </summary>
        public static string VersionIsRequired {
            get {
                return ResourceManager.GetString("VersionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version must be zero or more.
        /// </summary>
        public static string VersionMustBeZeroOrMore {
            get {
                return ResourceManager.GetString("VersionMustBeZeroOrMore", resourceCulture);
            }
        }
    }
}
